# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.15
_src_path: gh:rostools/template-workshop
author_family_name: Johnston
author_given_name: Luke
github_board_number: '12'
github_repo: r-cubed-advanced
github_user: rostools
workshop_type: r
