---
search: false
format: r3-theme-revealjs
---

# Welcome to the Advanced R^3^ course!

-   :heavy_check_mark: Go to your assigned table
-   :heavy_check_mark: Introduce yourselves to your table mates
-   :heavy_check_mark: Open your `AdvancedR3.Rproj` RStudio project
-   :heavy_check_mark: Just in case, do
    `r3::install_packages_advanced()`

::: notes
Introduce yourself and instructors.
:::

# Motivation for this course

## Largely from desire for more effective and actual collaboration {.center}

::: notes
Relate to UK Biobank project: <https://github.com/steno-aarhus/ukbAid>
:::

## But also from larger trends in research and society {.center}

### Like reproducibility

::: notes
Ask who knows what reproducibility is and could explain it.
:::

## Goal of course: Create and nurture a culture of openness through training {.center}

# Course details

## Setup and layout {.smaller}

::::: columns
::: {.column width="50%"}
-   Course is mix of:
    -   "Code-alongs" (we type and explain, you type along)
    -   Hands-on coding, discussing, and reading exercises
-   All material is online (and [openly
    licensed](https://r-cubed-advanced.rostools.org/LICENSE.html))
-   [Resources
    Appendix](https://r-cubed-advanced.rostools.org/resources.html)
    -   Material for further learning
:::

::: {.column width="50%"}
-   Less about coding, more about connecting with others
    -   Draw table name from bowl each morning
    -   Introduce yourself to those at your table
    -   During lunch, sit beside someone you don't know
    -   Several networking activities (usually after lunch)
-   *Warning*: You will be making a lot of functions!
:::
:::::

## Getting or asking for help :raising_hand_woman:

::::: columns
::: {.column width="50%"}
-   Put the sticky (a.k.a. tiny paper hat :womans_hat:) on your laptop
    to get help
-   There are lots of helpers
-   Table mates, help out too
:::

::: {.column width="50%"}
-   We're all learning here!
-   This is a supportive and safe environment
-   Remember our **Code of Conduct**
:::
:::::

. . .

> *Warning*: Those using OneDrive/Dropbox probably will encounter
> issues. Move project to Desktop?

## Practice using stickies: Did you complete the checklist from the beginning? {.center}

# Activities

## :walking_woman::walking_man: How do you perceive your skill in R? {.center}

::: notes
Along the wall, arrange to one side is "novice/basic" and other side is
"advanced".
:::

## :raising_hand_woman: Who has had formal training in specifically *coding* in R or in general? {.center}

::: notes
Staying where you are, raise your hand if you would answer yes to this
question. If it was part of a statistics course, it doesn't really
count.
:::

## :walking_woman::walking_man: Have you attended at least one of these courses before? {.center}

::: notes
Only have those who indicated they did have training (from previous
question).
:::

## :walking_woman::walking_man: How many of you work mostly on your own in your project(s)? {.center}

::: notes
Range from almost entirely alone to never alone.
:::

## :walking_woman::walking_man: How easy is it to collaborate with others on your project(s)? {.center}

## :walking_woman::walking_man: How many of you want to work more closely or collaboratively with others? {.center}

::: notes
Range from definitely no to definitely yes.
:::

## Alright, return to your seats! :chair: {.center}
