# Syllabus

Reproducibility and open scientific practices are increasingly demanded
of, and needed by, scientists and researchers in our modern research
environments. Our work environments and projects are also requiring or
involve a high level of hands-on collaboration on scientific projects
throughout all stages of the research lifecycle. We are faced with
obstacles that we have no training for nor knowledge on how to address
them. Obstacles that can be fairly simple, like not having a shared way
of writing code or managing files, can impede effective collaboration.
Or they can be complex, like documenting software dependencies or steps
in an analysis pipeline in a way that makes it easy to resolve and get
the most recent set of results after collaborators have worked on a
project. Even aside from the impact on collaboration, these barriers can
also affect projects with one primary researcher. Ultimately, this can
affect the reliability and reproducibility of scientific results,
especially considering that if these barriers are addressed, they are
often not explicitly shared in the science output like a publication.

With this course, we aim to begin addressing this gap. By using a highly
practical, hands-on approach that revolves around code-along sessions
(instructor and learner coding together), reading activities, and
hands-on exercises, our overarching **learning outcome** is that at the
end of the course, participants will be able to:

> Describe what an open, collaborator-friendly, and nearly-automated
> reproducible data analysis pipeline and workflow looks like, and then
> creating a project that follows these concepts by using R.

Our specific **learning outcomes** are to:

1.  Identify potential actions to take to streamline collaboration on a
    data analysis project and create projects that apply many of these
    actions using R.

2.  Describe and define the distinct steps involved in a pipeline that
    goes from raw data to final results, and to use R to build this
    pipeline in an automated and explicit way.

3.  Apply functional programming concepts to running statistical
    analyses that fit within the conceptual framework of automated
    pipelines and that can be used regardless of what statistical method
    is used.

4.  Explain the benefits of why scientific findings (and the pipelines)
    should be as easily accessible as possible and how a reproducible
    and automated pipeline can assist with making these findings
    accessible, by using R to build a website that displays your
    findings.

And we **will not** learn:

-   Specific statistical methods or models (these are already covered by
    most university curriculum).
-   Making figures or plots (data visualization could be a whole course
    on its own).

Because learning and coding is ultimately not *just* a solo activity,
during this course we also aim to provide opportunities to chat with
fellow participants, learn about their work and how they do analyses,
and to build networks of support and collaboration.

## Is this course for you?

This course is designed in a specific way and is ideal for you if:

-   You are a researcher, preferably working in the biomedical field
    (ranging from experimental to epidemiological). Specifically, this
    course targets those working on topics in diabetes and metabolism.
-   You currently do quantitative data analysis.
-   You preferably:
    -   have taken the [intermediate Reproducible Research in R
        course](https://r-cubed-intermediate.rostools.org/), as this
        course is a natural extension to that one;
    -   know a *moderate* or more amount of R (or computing in general);
    -   know how to use R and are fairly familiar with the
        [tidyverse](https://www.tidyverse.org/),
        [rmarkdown](https://rmarkdown.rstudio.com/),
        [RStudio](https://rstudio.com/), [Git](https://git-scm.com/),
        and [GitHub](https://github.com/).

Considering that this is a natural extension of the
[introductory](https://r-cubed.rostools.org/) and
[intermediate](https://r-cubed-intermediate.rostools.org/) r-cubed
courses, this course builds on the knowledge and skills learned during
those courses, including Git, RStudio R Projects, functions, functional
programming, and R Markdown. If you *do not* have familiarity with these
tools, you will need to go over the material from the introductory and
intermediate courses beforehand (more details about pre-course tasks
will be sent out a couple of weeks before the course).

While having these assumptions help to focus the content of the course,
if you have an interest in learning R but don't fit any of the above
assumptions, **you are still welcome to attend the course**! We welcome
everyone, that is until the course capacity is reached.
