---
execute:
  eval: false
---

```{r setup}
#| eval: true
#| include: false
library(tidyverse)
library(targets)
library(downlit)
library(pak)
```

# Pre-workshop tasks {#sec-pre-workshop}

In order to participate in this workshop, you must complete the pre-workshop
tasks in this section as well as **completing the
[survey](https://docs.google.com/forms/d/e/1FAIpQLSfzTLrLFyQHj79YGaCQDN5fUZ_9et1qdmtDGiq6gNPGzFSCyQ/viewform?usp=sf_link)**
at the end. These tasks are designed to make it easier for everyone to
start the workshop with everything ready to go. For some of the tasks, you
might not understand why you need to do them, but you will likely
understand why once the workshop begins.

Depending on your skills and knowledge, these tasks could take between
**5-7 hrs to finish**, so we suggest planning a full day to complete
them. Depending on your institution and how they handle installing
software on work computers, you also might have to contact IT *very
early* to make sure everything is properly installed and set up.

## List of tasks

Here's a quick overview of the tasks you need to do. Specific details
about them are found as you work through this section.

1.  Read the learning objectives in @sec-pre-workshop-learning-objectives
    for the pre-workshop tasks.
2.  Read about how to read this website in @sec-reading-website.
3.  Install the necessary programs and the right versions of those
    programs in @sec-install-programs. For some people, depending on
    their institution, this task can take the **longest amount of time**
    because you have to contact your IT to install these packages.
4.  Install the necessary R packages in @sec-install-r-packages.
5.  Correctly set up Git on your computer in @sec-setup-git, if you
    haven't done this already from previous workshops. If you haven't used
    Git before, this task could take a while because of the reading.
6.  Run a check with `r3::check_setup()` to see if everything works.
    You'll later need to paste this output into the survey.
7.  Connect your computer with GitHub in @sec-connect-github.
8.  Create an R Project in @sec-create-project, along with the folder
    and file setup.
9.  Create a Quarto file.
10. Write (well, mostly copy and paste) R code to download the data and
    save it to your computer. This task will probably take up maybe
    30-60 minutes depending on your interest in exploring the data.
11. Run a check using `r3::check_project_setup_advanced()` to see that
    everything is as expected. You'll later need to paste this output
    into the survey.
12. Set some options in RStudio in @sec-quality-of-life.
13. Read about the basic workshop details in @sec-workshop-details.
14. Read the syllabus in @sec-syllabus.
15. Read the [Code of
    Conduct](https://guides.rostools.org/conduct.html).
16. Pre-read some content in @sec-pre-reading.
17. **Complete the pre-workshop
    [survey](https://docs.google.com/forms/d/e/1FAIpQLSfzTLrLFyQHj79YGaCQDN5fUZ_9et1qdmtDGiq6gNPGzFSCyQ/viewform?usp=sf_link)**.
    This survey is pretty quick, maybe \~10 minutes.

Check each section for exact details on completing these tasks.

## Learning objective {#sec-pre-workshop-learning-objectives}

In general, these pre-workshop tasks are meant to help prepare you for the
workshop and make sure everything is setup properly so the first session
runs smoothly. However, some of these tasks are meant for learning as
well as for general setup, so we have defined the following learning
objectives for this page:

1.  Learn about and then apply some basic reproducible workflows and
    setups for the initial processing of raw data. For those who have
    already participated in the [intermediate R
    workshop](https://r-cubed-intermediate.rostools.org/), the objective
    is to review what you previously learned.

## Reading the workshop website {#sec-reading-website}

{{< include /includes/_reading-website.qmd >}}

## Set some quality of life options {#sec-quality-of-life}

Some of the most common "issues" we encounter in the workshop when it
comes to Git are caused by files not being saved so the changes can't be
seen by Git. To help with this, we suggest turning on some options in
RStudio. While, there are many options inside the Global Options in
RStudio that can help you work better and faster, the two we want you to
to use will help you and us out during the workshop:

-   Go into `Tools -> Global Options -> Code -> Saving`.
    -   Under the heading "General", tick on all of those check boxes.
    -   Under the heading "Auto-save", tick on both those check boxes.

## Workshop introduction {#sec-workshop-details}

Most of the workshop description is found in the syllabus (@sec-syllabus).
If you haven't read it, **please read it now**. Read over what the
workshop will cover, what we expect you to learn at the end of it, and
what our basic assumptions are about who you are and what you know. The
final pre-workshop task is to complete a survey that asks if you've read
it and if it matches you.

We have a [Code of Conduct](https://guides.rostools.org/conduct.html).
If you haven't read it, **read it now**. The survey at the end will ask
about Conduct. We want to make sure this workshop is a supportive and safe
environment for learning, so this Code of Conduct is important.

## Brief pre-reading {#sec-pre-reading}

An important component of learning is repeated exposure to a concept or
skill. So, while we will tell you this information during the workshop,
and in many cases you will also read it *during* the workshop, we want to
introduce some repetition here by reading the sections list below. This
will not only mentally prepare you for the content of the workshop, but
will also give you a bigger overview of what you will be learning and
doing. So, please read:

1.  The "big picture" in @sec-big-picture.
2.  Each sessions learning objectives:
    -   Collaboration: @sec-smoother-collaboration-learning-objectives.
    -   Pipelines: @sec-pipelines-learning-objectives.
    -   Analysis basics: @sec-stats-analyses-basic-learning-objectives.
    -   Multiple analyses:
        @sec-stats-analyses-multiple-learning-objectives.

## Fill in survey {#sec-survey}

You're almost done! :tada: Please fill out the [**pre-workshop
survey**](https://docs.google.com/forms/d/e/1FAIpQLSfzTLrLFyQHj79YGaCQDN5fUZ_9et1qdmtDGiq6gNPGzFSCyQ/viewform?usp=sf_link)
to finish this assignment.

See you at the workshop!

{{< include /_extensions/rostools/r3-theme/includes/code-appendix-r.qmd >}}
