---
format:
  r3-theme-html:
    tbl-colwidths: [30, 70]
---

# Schedule {#sec-schedule}

The course is structured as a series of participatory live-coding
sessions (instructor and learners coding together) interspersed with
hands-on exercises using a real-world, open dataset. There are few
lectures, only given at the start and end of the workshop.

The general schedule outline is shown in the below table. This is **not
a fixed schedule** of the timings of each session --- some may be
shorter and others may be longer. Instead, it is meant to be an
approximate guide and overview.

::: panel-tabset
## Day 1 {.unnumbered}

| Time | Session topic |
|:---|:---|
| 9:30 | {{< fa mug-hot >}} Arrival; Coffee and snacks |
| 10:00 | {{< fa person-chalkboard >}} [Introduction to the course](/sessions/introduction.qmd) |
| 10:30 | {{< fa laptop-code >}} [Smoother project-based collaboration (with short break)](/sessions/smoother-collaboration.qmd) |
| 12:20 | {{< fa comment-dots >}} [End of session survey](https://docs.google.com/forms/d/e/1FAIpQLScTbsxHSLrQxn38KS7kCklurFrccN8g3kVdm6WTSxEiIBypWg/viewform?usp=sf_link) |
| 12:30 | {{< fa utensils >}} Lunch |
| 13:15 | {{< fa user-group >}} [Networking and social activity](/appendix/social.qmd#social-day-one) |
| 13:35 | {{< fa laptop-code >}} [Continue previous session](/sessions/smoother-collaboration.qmd) |
| 15:00 | {{< fa mug-hot >}} Coffee break and snacks |
| 15:15 | {{< fa laptop-code >}} [Continue previous session](/sessions/smoother-collaboration.qmd) |
| 16:15 | {{< fa comment-dots >}} [End of session survey](https://docs.google.com/forms/d/e/1FAIpQLScTbsxHSLrQxn38KS7kCklurFrccN8g3kVdm6WTSxEiIBypWg/viewform?usp=sf_link) |

## Day 2 {.unnumbered}

| Time | Session topic |
|:---|:---|
| 9:00 | {{< fa laptop-code >}} [Short review; Creating automatic analysis pipelines](/sessions/pipelines.qmd) |
| 10:30 | {{< fa mug-hot >}} Coffee break and snacks |
| 10:45 | {{< fa laptop-code >}} [Continue previous session](/sessions/pipelines.qmd) |
| 12:20 | {{< fa comment-dots >}} [End of session survey](https://docs.google.com/forms/d/e/1FAIpQLScTbsxHSLrQxn38KS7kCklurFrccN8g3kVdm6WTSxEiIBypWg/viewform?usp=sf_link) |
| 12:30 | {{< fa utensils >}} Lunch |
| 13:15 | {{< fa user-group >}} [Networking and social activity](/appendix/social.qmd#social-day-two) |
| 13:35 | {{< fa laptop-code >}} [A general approach to doing statistical analyses](/sessions/stats-analyses-basic.qmd) |
| 15:00 | {{< fa mug-hot >}} Coffee break and snacks |
| 15:15 | {{< fa laptop-code >}} [Continue previous session](/sessions/stats-analyses-basic.qmd) |
| 16:15 | {{< fa comment-dots >}} [End of session survey](https://docs.google.com/forms/d/e/1FAIpQLScTbsxHSLrQxn38KS7kCklurFrccN8g3kVdm6WTSxEiIBypWg/viewform?usp=sf_link) |

## Day 3 {.unnumbered}

| Time | Session topic |
|:---|:---|
| 9:00 | {{< fa laptop-code >}} [Short review; Efficiently running many analyses at once](/sessions/stats-analyses-multiple.qmd) |
| 10:30 | {{< fa mug-hot >}} Coffee break and snacks |
| 10:45 | {{< fa laptop-code >}} [Continue previous session](/sessions/stats-analyses-multiple.qmd) |
| 12:20 | {{< fa comment-dots >}} [End of session survey](https://docs.google.com/forms/d/e/1FAIpQLScTbsxHSLrQxn38KS7kCklurFrccN8g3kVdm6WTSxEiIBypWg/viewform?usp=sf_link) |
| 12:30 | {{< fa utensils >}} Lunch |
| 13:15 | {{< fa people-group >}} [Team project work](/sessions/project-work.qmd) |
| 14:45 | {{< fa mug-hot >}} Coffee break and snacks |
| 15:00 | {{< fa people-group >}} [Continue team project work](/sessions/project-work.qmd) |
| 16:00 | {{< fa person-chalkboard >}} Closing remarks |
| 16:15 | {{< fa comment-dots >}} [End of course survey](https://docs.google.com/forms/d/e/1FAIpQLScTbsxHSLrQxn38KS7kCklurFrccN8g3kVdm6WTSxEiIBypWg/viewform?usp=sf_link) |
:::
