# Is this for you? {#sec-is-this-for-you}

To help manage expectations and develop the material for this workshop,
we make a few assumptions about *who you are* as a participant in the
workshop.

We assume you can relate to one or more of the following, which are the
expectations we've designed for this workshop.

-   You are a researcher, preferably working in the biomedical field
    (ranging from experimental to epidemiological). Specifically, this
    workshop targets those working on topics in diabetes and metabolism.
-   You currently do quantitative data analysis.
-   You preferably:
    -   have taken the [intermediate Reproducible Research in R
        workshop](https://r-cubed-intermediate.rostools.org/), as this
        workshop is a natural extension to that one;
    -   know a *moderate* or more amount of R (or computing in general);
    -   know how to use R and are fairly familiar with the
        `{tidyverse}`, [Quarto](https://quarto.org),
        [RStudio](https://rstudio.com/), [Git](https://git-scm.com/),
        and [GitHub](https://github.com/).

Considering that this is a natural extension of the
[introductory](https://r-cubed-intro.rostools.org/) and
[intermediate](https://r-cubed-intermediate.rostools.org/) r-cubed
workshops, this workshop builds on the knowledge and skills learned
during those workshops, including Git, RStudio R Projects, functions,
functional programming, and Quarto / R Markdown. If you *do not* have
familiarity with these tools, you will need to go over the material from
the introductory and intermediate workshops beforehand (more details
about pre-workshop tasks will be sent out a couple of weeks before the
workshop).

While we have these assumptions to help focus the content of the
workshop, if you have an interest in the workshop but don't fit any of
the assumptions, *you are still welcome to attend*! We welcome everyone
until capacity has been reached.
